#!/usr/bin/env python3
"""
Enhanced Desktop Data Entry Bot - BotCity + PyAutoGUI Integration
Combines BotCity's visual recognition with PyAutoGUI's automation
"""

import time
import requests
import pyautogui
import subprocess
import platform
from pathlib import Path

# BotCity imports
from botcity.core import DesktopBot

class EnhancedDesktopBot(DesktopBot):
    def __init__(self):
        # Initialize BotCity without configuration object
        super().__init__()
        
        # Configure PyAutoGUI for fast automation
        pyautogui.PAUSE = 0.05
        pyautogui.FAILSAFE = True
        
        # Detect operating system
        self.os_type = platform.system()
        print(f"🖥️  Detected OS: {self.os_type}")
        
        # Set up templates directory
        self.templates_dir = Path(__file__).parent / "templates"
        if not self.templates_dir.exists():
            print(f"⚠️  Templates directory not found: {self.templates_dir}")
        else:
            print(f"📸 Templates directory found: {self.templates_dir}")
        
        # Create project directory
        self.desktop_path = Path.home() / "Desktop"
        self.project_dir = self.desktop_path / "tjm-project"
        
        # Ensure directory exists
        if not self.project_dir.exists():
            print(f"📁 Creating project directory: {self.project_dir}")
            self.project_dir.mkdir(parents=True, exist_ok=True)
        else:
            print(f"📁 Project directory exists: {self.project_dir}")
        
        # Configure BotCity to use our templates directory
        self.add_image("textedit_window", str(self.templates_dir / "textedit_window.png"))
        self.add_image("save_dialog", str(self.templates_dir / "save_dialog.png"))
        self.add_image("save_button", str(self.templates_dir / "save_button.png"))
        self.add_image("use_both_extensions", str(self.templates_dir / "use_both_extensions.png"))
        self.add_image("use_both_extensions_button", str(self.templates_dir / "use_both_extensions_button.png"))
    
    def fetch_posts(self, limit=10):
        """Fetch blog posts from JSONPlaceholder API"""
        try:
            url = f"https://jsonplaceholder.typicode.com/posts?_limit={limit}"
            response = requests.get(url, timeout=10)
            response.raise_for_status()
            return response.json()
        except requests.RequestException as e:
            print(f"❌ Error fetching posts: {e}")
            return []
    
    def format_post_content(self, post):
        """Format API post data as a structured blog post"""
        title = post['title'].title()
        body = post['body'].replace('\n', '\n\n')
        
        content = f"""BLOG POST #{post['id']}

TITLE: {title}

CONTENT:
{body}

---
Post ID: {post['id']}
User ID: {post['userId']}
Generated by Enhanced Automation Bot
Platform: {self.os_type}
Date: {time.strftime('%Y-%m-%d %H:%M:%S')}
"""
        return content
    
    def launch_text_editor_with_verification(self):
        """Launch text editor and verify it opened using BotCity"""
        try:
            if self.os_type == "Darwin":  # macOS
                # Launch TextEdit
                subprocess.Popen(['open', '-a', 'TextEdit'])
                time.sleep(3)
                
                # Use BotCity to verify TextEdit opened
                if self.verify_textedit_opened():
                    print("✅ TextEdit verified to be open")
                    
                    # Create new document with PyAutoGUI
                    with pyautogui.hold(['command']):
                        time.sleep(0.1)
                        pyautogui.press('n')
                    time.sleep(2)
                    
                    # Set to plain text mode
                    with pyautogui.hold(['command']):
                        time.sleep(0.1)
                        pyautogui.press('shift')
                        pyautogui.press('t')
                    time.sleep(1)
                    
                    # Verify document is ready (I didn't implement this, but considered it in planning)
                    if self.verify_document_ready():
                        print("✅ Document ready for typing")
                        return True
                    else:
                        print("❌ Document not ready")
                        return False
                else:
                    print("❌ TextEdit failed to open")
                    return False
                    
            elif self.os_type == "Windows":  # Windows
                # Launch Notepad
                subprocess.Popen(['notepad.exe'])
                time.sleep(2)
                
                # Use BotCity to verify Notepad opened
                if self.verify_notepad_opened():
                    print("✅ Notepad verified to be open")
                    return True
                else:
                    print("❌ Notepad failed to open")
                    return False
                    
        except Exception as e:
            print(f"❌ Error launching text editor: {e}")
            return False
    
    def verify_textedit_opened(self):
        """Use BotCity template matching to verify TextEdit is open (macOS)"""
        try:
            print("🔍 Looking for TextEdit window using template matching...")
            
            # First try: Use template matching to find TextEdit window
            if self.find("textedit_window", matching=0.7, waiting_time=3000):
                print("✅ TextEdit window found using template matching")
                return True
            
            # Fallback 1: Use OCR to detect "TextEdit" text
            print("🔍 Template not found, trying OCR detection...")
            if self.find_text("TextEdit", matching=0.8, waiting_time=2000):
                print("✅ TextEdit detected using OCR")
                return True
            
            # Fallback 2: Look for "Format" menu (specific to TextEdit)
            if self.find_text("Format", matching=0.8, waiting_time=1000):
                print("✅ TextEdit Format menu detected")
                return True
            
            # Fallback 3: Look for File menu
            if self.find_text("File", matching=0.8, waiting_time=1000):
                print("✅ TextEdit File menu detected")
                return True
                
            print("❌ TextEdit window not detected with any method")
            return False
            
        except Exception as e:
            print(f"❌ Error verifying TextEdit: {e}")
            return False
    
    def verify_notepad_opened(self):
        """Use BotCity to verify Notepad is open (Windows)"""
        try:
            # Look for Notepad window
            if self.find_text("Notepad", matching=0.8, waiting_time=3000):
                return True
            
            # Look for Notepad's File menu
            if self.find_text("File", matching=0.8, waiting_time=1000):
                return True
                
            return False
            
        except Exception as e:
            print(f"❌ Error verifying Notepad: {e}")
            return False
    
    def verify_document_ready(self):
        """Verify document is ready for typing using BotCity"""
        try:
            # For TextEdit, check if we can see the text cursor or document area
            # This is a placeholder - you'd typically create a template image
            
            # Simple verification: wait a moment and assume ready
            time.sleep(1)
            return True
            
        except Exception as e:
            print(f"❌ Error verifying document ready: {e}")
            return False
    
    def type_content_with_verification(self, content):
        """Type content and verify it appears using BotCity OCR"""
        try:
            # Type content with PyAutoGUI (fast)
            print("⌨️  Typing content...")
            for char in content:
                pyautogui.write(char)
                time.sleep(0.001)  # Ultra-fast typing
            
            # Verify some content appeared using BotCity OCR
            time.sleep(1)  # Wait for text to appear
            
            # Look for the blog post title to verify typing worked
            if "BLOG POST #" in content:
                if self.verify_text_appeared("BLOG POST"):
                    print("✅ Content verified to appear on screen")
                    return True
                else:
                    print("⚠️  Content may not have appeared correctly")
                    return True  # Continue anyway
            
            return True
            
        except Exception as e:
            print(f"❌ Error typing content: {e}")
            return False
    
    def verify_text_appeared(self, text_to_find):
        """Use BotCity OCR to verify text appeared on screen"""
        try:
            # Use BotCity's OCR to find text on screen
            if self.find_text(text_to_find, matching=0.7, waiting_time=2000):
                return True
            return False
            
        except Exception as e:
            print(f"❌ Error verifying text: {e}")
            return False
    
    def save_with_verification(self, filename):
        """Save document and verify save dialog using BotCity"""
        try:
            if self.os_type == "Darwin":  # macOS
                # Open save dialog with PyAutoGUI
                with pyautogui.hold(['command']):
                    time.sleep(0.1)
                    pyautogui.press('s')
                time.sleep(2)
                
                # Use BotCity to verify save dialog appeared
                if self.verify_save_dialog_opened():
                    print("✅ Save dialog verified to be open")
                    
                    # Clear and type file path with PyAutoGUI
                    with pyautogui.hold(['command']):
                        time.sleep(0.1)
                        pyautogui.press('a')
                    time.sleep(0.5)
                    
                    file_path = str(self.project_dir / filename)
                    print(f"💾 Saving to: {file_path}")
                    
                    for char in file_path:
                        pyautogui.write(char)
                        time.sleep(0.001)
                    
                    time.sleep(1)
                    pyautogui.press('enter')
                    time.sleep(2)
                    
                    # Try to click Save button if available
                    if self.click_save_button():
                        print("✅ Save button clicked successfully")
                    
                    # Handle potential extension dialog (macOS TextEdit specific)
                    time.sleep(1)  # Wait for potential dialog
                    extension_handled = self.handle_extension_dialog()
                    if extension_handled:
                        print("✅ Extension dialog handled successfully")
                        self.take_evidence_screenshot("extension_dialog_resolved")
                    
                    # Verify file was saved
                    if self.verify_file_saved(filename):
                        print(f"✅ File {filename} verified to be saved")
                        return True
                    else:
                        print(f"❌ File {filename} may not have saved correctly")
                        return False
                else:
                    print("❌ Save dialog failed to open")
                    return False
                    
            elif self.os_type == "Windows":  # Windows
                # Similar implementation for Windows
                pyautogui.hotkey('ctrl', 's')
                time.sleep(2)
                
                if self.verify_save_dialog_opened():
                    pyautogui.hotkey('ctrl', 'a')
                    time.sleep(0.5)
                    
                    file_path = str(self.project_dir / filename)
                    for char in file_path:
                        pyautogui.write(char)
                        time.sleep(0.001)
                    
                    pyautogui.press('enter')
                    time.sleep(2)
                    
                    return self.verify_file_saved(filename)
                else:
                    return False
                    
        except Exception as e:
            print(f"❌ Error saving document: {e}")
            return False
    
    def verify_save_dialog_opened(self):
        """Use BotCity template matching to verify save dialog is open"""
        try:
            print("🔍 Looking for save dialog using template matching...")
            
            # First try: Use template matching to find save dialog
            if self.find("save_dialog", matching=0.7, waiting_time=3000):
                print("✅ Save dialog found using template matching")
                return True
            
            # Fallback 1: Look for save dialog indicators using OCR
            print("🔍 Template not found, trying OCR detection...")
            if self.find_text("Save", matching=0.8, waiting_time=2000):
                print("✅ Save dialog detected using OCR")
                return True
            
            # Fallback 2: Look for file name field or browse buttons
            if self.find_text("File name", matching=0.7, waiting_time=1000):
                print("✅ File name field detected")
                return True
            
            # Fallback 3: Look for common save dialog elements
            save_indicators = ["Save As", "Where:", "Format:"]
            for indicator in save_indicators:
                if self.find_text(indicator, matching=0.7, waiting_time=500):
                    print(f"✅ Save dialog indicator '{indicator}' detected")
                    return True
                
            print("❌ Save dialog not detected with any method")
            return False
            
        except Exception as e:
            print(f"❌ Error verifying save dialog: {e}")
            return False
    
    def handle_extension_dialog(self):
        """Handle macOS extension dialog that appears when saving .txt files"""
        try:
            print("🔍 Checking for extension dialog...")
            
            # First check if the extension dialog appeared
            if self.find("use_both_extensions", matching=0.7, waiting_time=3000):
                print("📄 Extension dialog detected - TextEdit wants to use .rtf")
                
                # Take evidence screenshot
                self.take_evidence_screenshot("extension_dialog_detected")
                
                # Try to click "Use Both" button using template
                if self.find("use_both_extensions_button", matching=0.8, waiting_time=2000):
                    print("✅ Found 'Use Both' button, clicking...")
                    self.click()
                    time.sleep(1)
                    return True
                else:
                    print("⚠️  'Use Both' button template not found, trying OCR...")
                    # Fallback: Look for "Use Both" text and click it
                    if self.find_text("Use Both", matching=0.8, waiting_time=2000):
                        print("✅ Found 'Use Both' text via OCR, clicking...")
                        self.click()
                        time.sleep(1)
                        return True
                    else:
                        print("🔄 Using keyboard navigation as fallback...")
                        # Keyboard fallback - "Use Both" is typically the middle button
                        pyautogui.press('tab')  # Navigate to Use Both
                        pyautogui.press('enter')
                        time.sleep(1)
                        return True
            else:
                print("✅ No extension dialog detected")
                return False
                
        except Exception as e:
            print(f"❌ Error handling extension dialog: {e}")
            return False
    
    def click_save_button(self):
        """Try to click save button using template matching"""
        try:
            print("🔍 Looking for Save button using template...")
            
            # Try to find and click the save button template
            if self.find("save_button", matching=0.8, waiting_time=2000):
                print("✅ Save button found using template, clicking...")
                self.click()
                time.sleep(1)
                return True
            else:
                print("⚠️  Save button template not found, using Enter key...")
                # Fallback to Enter key
                return False
                
        except Exception as e:
            print(f"❌ Error clicking save button: {e}")
            return False
    
    def verify_file_saved(self, filename):
        """Verify file was actually saved to disk"""
        try:
            file_path = self.project_dir / filename
            # Check if file exists and has content
            if file_path.exists() and file_path.stat().st_size > 0:
                return True
            return False
            
        except Exception as e:
            print(f"❌ Error verifying file saved: {e}")
            return False
    
    def take_evidence_screenshot(self, step_name, post_id=None):
        """Take screenshot for evidence and debugging, saving to evidence folder."""
        try:
            from PIL import ImageGrab
            # Create evidence directory
            evidence_dir = self.project_dir / "evidence"
            evidence_dir.mkdir(exist_ok=True)

            # Take screenshot using PIL.ImageGrab
            screenshot = ImageGrab.grab()

            # Create descriptive filename
            timestamp = time.strftime('%Y%m%d_%H%M%S')
            if post_id:
                evidence_filename = f"post_{post_id}_{step_name}_{timestamp}.png"
            else:
                evidence_filename = f"{step_name}_{timestamp}.png"
            evidence_path = evidence_dir / evidence_filename

            # Save screenshot to evidence folder
            screenshot.save(evidence_path)
            print(f"📸 Evidence screenshot saved: {evidence_path}")
            return str(evidence_path)
        except Exception as e:
            print(f"❌ Error taking evidence screenshot: {e}")
            return None
    
    def close_editor_safely(self):
        """Close text editor with verification and smart dialog handling"""
        try:
            if self.os_type == "Darwin":  # macOS
                print("🔄 Closing TextEdit window...")
                with pyautogui.hold(['command']):
                    time.sleep(0.1)
                    pyautogui.press('w')
                time.sleep(1)
                
                # Handle "Don't Save" dialog if it appears
                print("🔍 Checking for save confirmation dialog...")
                if self.find_text("Don't Save", matching=0.8, waiting_time=2000):
                    print("💾 Save confirmation dialog detected")
                    
                    # Try to click "Don't Save" button using template
                    if self.find("save_button", matching=0.8, waiting_time=1000):
                        print("✅ Found Don't Save button, clicking...")
                        self.click()
                    else:
                        print("🔄 Using keyboard navigation for Don't Save...")
                        # Fallback to keyboard navigation
                        pyautogui.press('tab')
                        pyautogui.press('tab')
                        pyautogui.press('enter')
                else:
                    print("✅ No save confirmation dialog appeared")
                
            elif self.os_type == "Windows":  # Windows
                print("🔄 Closing Notepad window...")
                pyautogui.hotkey('alt', 'f4')
                time.sleep(1)
                
                # Handle save prompt
                print("🔍 Checking for save confirmation dialog...")
                if self.find_text("Do you want to save", matching=0.8, waiting_time=2000):
                    print("💾 Save confirmation dialog detected, selecting No...")
                    pyautogui.press('n')  # No, don't save
                else:
                    print("✅ No save confirmation dialog appeared")
                    
        except Exception as e:
            print(f"❌ Error closing editor: {e}")
    
    def process_single_post(self, post):
        """Process a single post with full BotCity verification and evidence collection"""
        print(f"📝 Processing Post {post['id']}: {post['title'][:50]}...")
        
        # Take initial screenshot
        self.take_evidence_screenshot("start_processing", post['id'])
        
        # Launch and verify text editor
        if not self.launch_text_editor_with_verification():
            print(f"❌ Failed to launch/verify text editor for post {post['id']}")
            self.take_evidence_screenshot("launch_failed", post['id'])
            return False
        
        # Take screenshot after successful launch
        self.take_evidence_screenshot("editor_opened", post['id'])
        
        try:
            # Format content
            content = self.format_post_content(post)
            
            # Type content with verification
            if not self.type_content_with_verification(content):
                print(f"❌ Failed to type content for post {post['id']}")
                self.take_evidence_screenshot("typing_failed", post['id'])
                return False
            
            # Take screenshot after typing
            self.take_evidence_screenshot("content_typed", post['id'])
            
            # Save with verification
            filename = f"post {post['id']}.txt"
            if self.save_with_verification(filename):
                print(f"✅ Successfully processed post {post['id']}")
                self.take_evidence_screenshot("save_success", post['id'])
                self.close_editor_safely()
                return True
            else:
                print(f"❌ Failed to save post {post['id']}")
                self.take_evidence_screenshot("save_failed", post['id'])
                self.close_editor_safely()
                return False
                
        except Exception as e:
            print(f"❌ Error processing post {post['id']}: {e}")
            self.take_evidence_screenshot("error_occurred", post['id'])
            self.close_editor_safely()
            return False
    
    def run_automation(self):
        """Main automation workflow with BotCity integration"""
        print("🚀 Starting Enhanced Desktop Automation Bot...")
        print("🤖 BotCity + PyAutoGUI Integration")
        print("=" * 60)
        
        # Display capabilities
        if self.os_type == "Darwin":
            print("🍎 Using TextEdit on macOS")
            print("🔍 BotCity: Visual verification and OCR")
            print("⚡ PyAutoGUI: Fast keyboard automation")
        elif self.os_type == "Windows":
            print("🪟 Using Notepad on Windows")
            print("🔍 BotCity: Visual verification and OCR")
            print("⚡ PyAutoGUI: Fast keyboard automation")
        
        # Fetch posts
        print("🌐 Fetching posts from JSONPlaceholder API...")
        posts = self.fetch_posts(10)
        
        if not posts:
            print("❌ No posts retrieved. Exiting.")
            return
        
        print(f"📋 Retrieved {len(posts)} posts")
        print("=" * 60)
        
        # Process posts with full verification
        successful_posts = 0
        failed_posts = 0
        
        for i, post in enumerate(posts, 1):
            print(f"\n[{i}/10] Processing post {post['id']}...")
            
            if self.process_single_post(post):
                successful_posts += 1
            else:
                failed_posts += 1
            
            time.sleep(1)  # Brief pause between posts
        
        # Final summary
        print("\n" + "=" * 60)
        print("🎉 ENHANCED AUTOMATION COMPLETE")
        print(f"✅ Successful: {successful_posts} posts")
        print(f"❌ Failed: {failed_posts} posts")
        print(f"📁 Files saved to: {self.project_dir}")
        print("🔍 All operations verified with BotCity")
        print("📸 Template matching used for robust UI detection")
        
        # List created files
        if successful_posts > 0:
            print("\n📄 Created and verified files:")
            for file in sorted(self.project_dir.glob("post *.txt")):
                print(f"  - {file.name}")
        
        # Evidence collection summary
        evidence_dir = self.project_dir / "evidence"
        if evidence_dir.exists():
            evidence_count = len(list(evidence_dir.glob("*.png")))
            print(f"\n📸 Evidence screenshots collected: {evidence_count}")
            print(f"📁 Evidence location: {evidence_dir}")

def main():
    """Main function with enhanced error handling"""
    try:
        print("🤖 Enhanced Desktop Automation Bot Starting...")
        print("🔧 BotCity + PyAutoGUI Integration")
        print("⚠️  IMPORTANT: Move your mouse to the top-left corner to stop")
        
        os_type = platform.system()
        if os_type == "Darwin":
            print("🍎 macOS: Using TextEdit with visual verification")
        elif os_type == "Windows":
            print("🪟 Windows: Using Notepad with visual verification")
        
        print("⏰ Starting in 3 seconds...")
        for i in range(3, 0, -1):
            print(f"{i}...")
            time.sleep(1)
        
        # Create and run enhanced bot
        bot = EnhancedDesktopBot()
        bot.run_automation()
        
    except KeyboardInterrupt:
        print("\n⏹️  Bot stopped by user")
    except Exception as e:
        print(f"💥 Unexpected error: {e}")
    finally:
        print("🏁 Enhanced bot terminated")

if __name__ == "__main__":
    main() 